### ISSUE TITLE
Problem with routeNotFoundCallback

### ISSUE THREAD

**Issue by dre1080** [jeffturcotte/moor#10]
the header("HTTP/1.1 404 Not Found"); in Moor.php causes a broken link error on chrome, this will not be good for users using Google chrome, unable to debug when using chrome..works fine in IE and FF
when i removed it it worked fine on google chrome, still looking for a workaround to send 404 headers and not break on Chrome

**Comment by wbond** [comment]
Do you have an example URL of this header() call breaking chrome? I've used Moor and triggered the not found callback and it seems to work OK in chrome.

I should be able to commit a fix if I can understand what is going on.

**Comment by mattsah** [comment]
Some browsers display their own custom pages if the entire size of the returned result is too small, this is likely the case with Moor's built in not found callback.  That said, it is not the header causing the issue, but is rather the fact that Moor has a very small NOT found page by default, which some browsers will ignore as "useless" and present their own errors for.

I am closing this unless proven otherwise.
